# -*- coding: utf-8 -*-
# Copyright (c) 2024, Aboubaker Tamessouct and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document
from erpnextwats.erpnextwats.api import log_info, log_error

class WhatsAppTemplate(Document):
    def on_update(self):
        """
        Auto-generate or update the Client Script for the target DocType.
        This ensures the WhatsApp button appears immediately without 'bench build'.
        """
        if not self.doctype_name:
            return

        script_name = f"WhatsApp Integration for {self.doctype_name}"
        
        # Check if script exists
        if not frappe.db.exists("Client Script", {"dt": self.doctype_name, "name": script_name}):
            # Create new Client Script
            doc = frappe.new_doc("Client Script")
            doc.dt = self.doctype_name
            doc.name = script_name
            doc.enabled = 1
            doc.view = "Form"
        else:
            # Fetch existing to update
            doc = frappe.get_doc("Client Script", script_name)
            
        # The JS Code to inject
        # This code uses built-in Frappe API + erpnextwats.api checks
        js_code = f"""
// Auto-generated by WhatsApp Template: {self.name}
frappe.ui.form.on('{self.doctype_name}', {{
    refresh: function(frm) {{
        // Basic checks: Saved doc
        if (frm.is_new()) return;

        // Add Button
        if (!frm.custom_buttons || !frm.custom_buttons[__('WhatsApp')]) {{
            frm.add_custom_button(__('WhatsApp'), function() {{
                // Fetch templates dynamically
                frappe.call({{
                    method: 'erpnextwats.erpnextwats.api.get_templates',
                    args: {{ doctype: frm.doctype }},
                    callback: function(r) {{
                        const templates = r.message || [];
                        if (!templates.length) {{
                            frappe.msgprint(__('No templates found for ' + frm.doctype));
                            return;
                        }}

                        // Get customer phone number
                        let customer_phone = frm.doc.mobile_no || frm.doc.phone || frm.doc.contact_mobile || '';
                        
                        // If single template, send directly (after checking phone)
                        if (templates.length === 1) {{
                            if (!customer_phone && frm.doc.customer) {{
                                frappe.call({{
                                    method: 'frappe.client.get',
                                    args: {{
                                        doctype: 'Customer',
                                        name: frm.doc.customer
                                    }},
                                    callback: function(cust_r) {{
                                        customer_phone = cust_r.message.mobile_no || cust_r.message.phone || '';
                                        if (!customer_phone) {{
                                            frappe.msgprint({{
                                                title: __('No Phone Number'),
                                                message: __('Customer does not have a registered phone number. Please add a phone number to the customer.'),
                                                indicator: 'orange'
                                            }});
                                            return;
                                        }}
                                        sendWhatsAppMessage(frm, templates[0].name, customer_phone);
                                    }}
                                }});
                            }} else if (!customer_phone) {{
                                frappe.msgprint({{
                                    title: __('No Phone Number'),
                                    message: __('This document does not have a registered phone number. Please add a phone number.'),
                                    indicator: 'orange'
                                }});
                                return;
                            }} else {{
                                sendWhatsAppMessage(frm, templates[0].name, customer_phone);
                            }}
                        }} else {{
                            // Multiple templates - show dialog with preview
                            showTemplateDialog(frm, templates, customer_phone);
                        }}
                    }}
                }});
            }});
            
            // Style the button (Green)
            setTimeout(() => {{
                frm.page.get_inner_group_button(__('WhatsApp'))
                    .removeClass('btn-default')
                    .addClass('btn-success')
                    .css({{'background-color': '#25D366', 'color': 'white', 'border-color': '#25D366'}});
            }}, 100);
        }}
    }}
}});

function sendWhatsAppMessage(frm, template_id, phone) {{
    frappe.show_alert({{ message: __('Sending WhatsApp...'), indicator: 'blue' }});
    frappe.call({{
        method: 'erpnextwats.erpnextwats.api.send_via_template',
        args: {{
            docname: frm.doc.name,
            doctype: frm.doctype,
            template_id: template_id,
            phone: phone
        }},
        callback: function(r) {{
            if (r.message && r.message.status === 'success') {{
                frappe.show_alert({{ message: __('Message sent!'), indicator: 'green' }});
            }} else {{
                frappe.msgprint({{
                    title: __('Error'),
                    message: r.message ? r.message.message : __('Unknown error'),
                    indicator: 'red'
                }});
            }}
        }}
    }});
}}

function showTemplateDialog(frm, templates, customer_phone) {{
    if (!customer_phone && frm.doc.customer) {{
        frappe.call({{
            method: 'frappe.client.get',
            args: {{
                doctype: 'Customer',
                name: frm.doc.customer
            }},
            callback: function(cust_r) {{
                customer_phone = cust_r.message.mobile_no || cust_r.message.phone || '';
                if (!customer_phone) {{
                    frappe.msgprint({{
                        title: __('No Phone Number'),
                        message: __('Customer does not have a registered phone number. Please add a phone number to the customer.'),
                        indicator: 'orange'
                    }});
                    return;
                }}
                createTemplateDialog(frm, templates, customer_phone);
            }}
        }});
    }} else if (!customer_phone) {{
        frappe.msgprint({{
            title: __('No Phone Number'),
            message: __('This document does not have a registered phone number. Please add a phone number.'),
            indicator: 'orange'
        }});
        return;
    }} else {{
        createTemplateDialog(frm, templates, customer_phone);
    }}
}}

function createTemplateDialog(frm, templates, phone) {{
    const dialog = new frappe.ui.Dialog({{
        title: __('Send ' + frm.doctype + ' via WhatsApp'),
        fields: [
            {{
                label: __('Select Template'),
                fieldname: 'template_id',
                fieldtype: 'Select',
                options: templates.map(t => ({{ label: t.template_name, value: t.name }})),
                reqd: 1,
                change: function() {{
                    // Show preview when template changes
                    if (this.get_value()) {{
                        frappe.call({{
                            method: 'erpnextwats.erpnextwats.api.render_template_preview',
                            args: {{
                                doctype_name: frm.doctype,
                                message: templates.find(t => t.name === this.get_value()).message || '',
                                docname: frm.doc.name
                            }},
                            callback: function(preview_r) {{
                                if (preview_r.message) {{
                                    dialog.fields_dict.preview_html.$wrapper.html(
                                        '<div style="background: #e5ddd5; padding: 15px; border-radius: 8px; margin-top: 10px;">' +
                                        '<div style="background: #fff; padding: 10px; border-radius: 8px; white-space: pre-wrap; font-size: 14px;">' +
                                        preview_r.message.replace(/\\n/g, '<br>') +
                                        '</div></div>'
                                    );
                                }}
                            }}
                        }});
                    }}
                }}
            }},
            {{
                fieldname: 'preview_html',
                fieldtype: 'HTML',
                label: __('Preview')
            }}
        ],
        primary_action_label: __('Send Now'),
        primary_action: function(data) {{
            sendWhatsAppMessage(frm, data.template_id, phone);
            dialog.hide();
        }}
    }});
    dialog.show();
}}
"""
        doc.script = js_code
        doc.save(ignore_permissions=True)
        
        # Log template update
        action = "created" if self.is_new() else "updated"
        log_info(
            activity_type=f"Template {action.capitalize()}",
            template=self.name,
            reference_doctype="WhatsApp Template",
            reference_name=self.name,
            metadata={
                "template_name": self.template_name,
                "doctype_name": self.doctype_name,
                "action": action,
                "client_script": script_name,
                "is_auto_send": self.enable_auto_send if hasattr(self, 'enable_auto_send') else False
            }
        )

    def before_delete(self):
        """Log template deletion before it happens."""
        try:
            # Delete the associated client script
            script_name = f"WhatsApp Integration for {self.doctype_name}"
            if frappe.db.exists("Client Script", script_name):
                frappe.delete_doc("Client Script", script_name, ignore_permissions=True)
            
            # Log the deletion
            log_info(
                activity_type="Template Deleted",
                template=self.name,
                reference_doctype="WhatsApp Template",
                reference_name=self.name,
                metadata={
                    "template_name": self.template_name,
                    "doctype_name": self.doctype_name,
                    "client_script_removed": script_name
                }
            )
        except Exception as e:
            log_error(
                activity_type="Template Delete Error",
                error=e,
                template=self.name,
                metadata={"step": "before_delete"}
            )

